# Generated by Django 3.2.12 on 2023-07-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='schools',
            new_name='school',
        ),
    ]
